config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#root"  
  
  namespace :api, defaults: {format: :json} do
    resources :users, only: [:index, :show, :update] 
    resources :paralegals, only: [:index, :show]
    resources :teams, only: [:index, :show, :update]
  end
  
  resources :teams, only: [:new, :create]
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  
  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                  :integer          not null, primary key
#  fname               :string(255)      not null
#  lname               :string(255)      not null
#  password_digest     :string(255)      not null
#  email               :string(255)      not null
#  session_token       :string(255)      not null
#  created_at          :datetime
#  updated_at          :datetime
#  team_id             :integer
#  money               :integer
#  avatar_file_name    :string(255)
#  avatar_content_type :string(255)
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#

class User < ActiveRecord::Base

  attr_reader :password, :avatar 
  validates :fname, :lname, :password_digest, presence: :true
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: :true}

  before_validation :ensure_session_token

  has_many :team_memberships, inverse_of: :user 
  has_many :teams, through: :team_memberships, source: :team
  has_many :sponsorships, inverse_of: :user, dependent: :destroy 
  has_many :paralegals, through: :sponsorships, source: :paralegal

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "50x50>" }, :default_url => "/images/:style/guest.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_attachment_file_name :avatar, :matches => [/png\Z/, /jpe?g\Z/]

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    user.try(:is_password?, password) ? user : nil 
  end

  def password=(plainText)
    @password = plainText
    self.password_digest = BCrypt::Password.create(@password)
  end

  def is_password?(plaintext)
    BCrypt::Password.new(self.password_digest).is_password?(plaintext)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token 
  end

  def total_sponsorships
    donations = self.sponsorships.map{|sponsorship| sponsorship.donation}
    donations.inject{|sum, donation| sum + donation}
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApiController
    
    def index
      @users = User.all
      render :index  
    end

    def show
      @user = User.find(params[:id])
      @paralegals = @user.paralegals
      @teams = @user.teams
      render "api/users/show", locals: {user: @user}
    end

    def update

      if params[:sponsorship] == ""
        @user = current_user
        @user.update_attributes(user_params)
        render partial: "api/users/user", locals: {user: @user}
      
      else 
        @user = current_user
        @paralegal = Paralegal.find(params[:sponsorship])
        money = params[:money]
        @sponsorship = Sponsorship.new

        ActiveRecord::Base.transaction do 
          @user.update_attributes(user_params) 
          @paralegal.update_attributes(money: params[:amount] )  
          if !@user.paralegals.include?(@paralegal)
           @sponsorship = Sponsorship.new(user_id: @user.id, donation: params[:donation], paralegal_id: params[:sponsorship])
           @sponsorship.save!
          else
            @sponsorship = Sponsorship.where(user_id: @user.id, paralegal_id: @paralegal.id).first
            new_donation = @sponsorship.donation + params[:donation]
            @sponsorship.update_attributes(donation: new_donation)
          end
        end 

        if (@user.errors.full_messages.length + @sponsorship.errors.full_messages.length + @paralegal.errors.full_messages.length) == 0
          render partial: "api/users/user", locals: {user: @user} 
        else
          render json: { user_errors: @user.errors.full_messages, paralegal_errors: @paralegal.errors.full_messages, sponsor_errors: @sponsorship.errors.full_messages }, status: 422
        end
      end
    end
    
    private

    def user_params
      params.require(:user).permit(:money) 
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :fname, :lname, :password, :avatar)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<style>

body{
  background-color: #f7f7f2;
}

.btn-primary{
  background: orange;
}

h3{
  color: #4b9123;
  font-family: 'Proxima Nova Regular', 'Helvetica Neue', Arial, Helvetica, sans-serif;
  font-size: 1.4286em;
  font-size-adjust: 0.488;
  font-weight: 400;
}

div{
  color: #333;
}

.col-md-4{
 border-radius: 10px;
 border: 1px solid gray;
 background: white;
}

#subscript{
  font-size: .75em;
}

label{
  font-family: 'Proxima Nova Regular', 'Helvetica Neue', Arial, Helvetica, sans-serif;
  font-size: 1em;
  font-size-adjust: 0.488;
  font-weight: 400;
}

.password-field{
  margin-bottom: 10px;
}

.row{
  margin-top: 100px;
}

#sign-up-box{
  -webkit-box-shadow: 0px -2px 8px -4px #888, 1px 1px 4px #ccc;
  box-shadow: 0px -2px 8px -4px #888, 1px 1px 4px #ccc;
  border: #ccc 1px solid;
}

#avatar-form{
  margin-bottom: 10px;
}

</style>

<div class="container">
  <div class="row">
    <div id="sign-up-box" class="col-md-4 col-md-offset-4"> 
      <%= render "layouts/errors" %>
      Already a member? <a href="<%= new_session_url %>">Sign in</a><br>
      <h3>Sign up</h3><div id="subscript">* required fields </div>
      <%= form_for @user, :url => users_path, :html => { :multipart => true } do |form| %>
        <%= form.label :fname, "First Name*"%><br>
        <%= form.text_field :fname %>
        <br>
        <%= form.label :lname, "Last Name*"%><br>
        <%= form.text_field :lname%>
        <br>
        <%= form.label :email, "Email*"%><br>
        <%= form.text_field :email %>
        <br>
        <%= form.label :password, "Password*"%><br>
        <%= form.password_field :password %>
        <br>
        <%= form.label :avatar, "Profile picture"%>
        <div id="avatar-form">
          <%= form.file_field :avatar %>
        </div>
        <%= form.submit :create, value: "Create User", class: "btn btn-primary" %>
      <% end %>

      </div>
    </div>
</div>