config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#root"  
  
  namespace :api, defaults: {format: :json} do
    resources :users, only: [:index, :show, :update] 
    resources :paralegals, only: [:index, :show]
    resources :teams, only: [:index, :show, :update]
  end
  
  resources :teams, only: [:new, :create]
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  
  

end

app/views/layouts/_errors.html.erb
<% flash[:errors] && flash[:errors].each do |error| %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" 
      class="close" 
      data-dismiss="alert" 
      aria-hidden="true">&times;</button>
    <strong>Error:</strong>
    <%= error %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<style>

nav.navbar{
  border-bottom: #4b9123 5px solid;
  margin-bottom: 0px; 
}

li{
  margin-left: 15px;
  margin-right: 15px;
}

.btn-xs{
  margin-top: 13px;
}

.navbar-nav{
  font-family: 'Proxima Nova Light', 'Helvetica Neue', Arial, Helvetica, sans-serif;
  font-size: 1.25em;
  font-size-adjust: 0.488;
  font-weight: 200;
}

.btn-xs{
  margin-right: 5px;
}

#current-money{
  float: left;
}

#bottom-strip{
  height: 35px;
  border-bottom: none;
  padding-bottom: none;
  font-size: 1.4em;
}

#bottom-tagline{
  color: white;
  padding-top: 5px;
  padding-left: 111px;
}

.footer{
  background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0, #f7f7f2), color-stop(1, #c2e5a2));
  background-image: -ms-linear-gradient(top, #f7f7f2 0%, #c2e5a2 100%);
  background-image: linear-gradient(top, #f7f7f2, #c2e5a2);
  background-repeat: no-repeat;
  background-position: bottom;

  min-height: 300px;
  padding: 0px;
}

#tagline{
  padding-top: 14px;
  padding-left: 111px;
}

.head-strip{
  font-family:"Museo Slab 300", Rockwell, Georgia, serif;
  font-weight:300;
  font-style:normal;
  font-size:1.8em;
  color: white;
  background: #74b446;
  height: 70px;
  margin-left: 0;
  margin-right: 0;
}

.hidden-elements{
  display: none;
}

#content {
  font: .875em/1.357 arial, helvetica, sans-serif;
}

#home-page-info{
  margin-top: 100px;
  margin-bottom: 100px;
  padding-top: 10px;
  background-color: white;
  -webkit-box-shadow: 0px -2px 8px -4px #888, 1px 1px 4px #ccc;
  border: #ccc 1px solid;
  margin-right: 15px;
  margin-left: 15px;
}

#about-box{
  font-family: 'Proxima Nova Regular', 'Helvetica Neue', Arial, Helvetica, sans-serif;
  font-size: 2em;
  font-size-adjust: 0.488;
  color: #4b9123;
}

#about-header {
  font-size: .9em;
  font-weight: 300;
}

#about-link{
  float: right;
  line-height: 1.25em;
  font-weight: 200;
  margin-top: 2px;
}

.about-list{
  list-style: none;
  color: #333;
}

.number{
  background-color: #74b446;
  color: #fff;
  display: inline-block;
  margin-right: 10px;
  padding: 3px;
  width: 47px;
  height: 47px;
  text-align: center;
  -moz-border-radius: 50px;
  -webkit-border-radius: 5px;
  border-radius: 50px;
  font-family: "Museo Slab 500", Rockwell, Georgia, serif;
  font-weight: 500;
  font-size: 2em;
  line-height: 1.25em;
  padding: 3px;
  margin-bottom: 8px;
}

.home-list-item{
  margin-top: 10px;
  margin-bottom: 10px;
  font-size: 1.8em;
  line-height: 1.428571429;
  font-family: 'Proxima Nova Light', 'Helvetica Neue', Arial, Helvetica, sans-serif;
  font-size-adjust: 0.488;
  font-weight: 200;
  min-height: 400px;
}

#about-text{
  font-size: 1.3em;
}

#about-block{
  padding-bottom: 45px;
}

#home-index-button{
  line-height: 1.9em;
  padding-right: 1.4em;
  padding-left: 1.4em;
  -moz-border-radius: 2em;
  -webkit-border-radius: 2em;
  border-radius: 2em;
  border-width: 1px;
  border-style: solid;
  cursor: pointer;
  display: inline-block;
  outline: none;
  vertical-align: bottom;
  -webkit-user-select: none;
  -khtml-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  background-image: -webkit-gradient(linear,left top,left bottom,color-stop(0, #ffffff),color-stop(1, #e1e1e1));
  background-color: #f1efed;
  border-color: #74b446;
  color: #4b9123;
  font-family: 'Proxima Nova Regular', 'Helvetica Neue', Arial, Helvetica, sans-serif;
  font-weight: 400;
  font-size: 1.4286em;
  text-decoration: none;
  margin-left: 13px;
}

#home-index-button:hover{
   background-image: -webkit-gradient(linear,left top,left bottom,color-stop(0, #ffffff),color-stop(1, #74b446));
}

</style>

<% if current_user %>
<script type="text/javascript">
  window.currentUser = {
    id: "<%=current_user.id%>"
  }
</script>
<% end %>

<!DOCTYPE html>
<html>
<head>
  <title>Kiva for Paralegals</title>
  <%= stylesheet_link_tag    'application'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Kiva for Paralegals</a>
      </div>

      <div class="nav navbar-nav">
        <li><a class="navbar-link" href="#paralegals/index">Give</a></li>
        <li><a class="navbar-link" href="#about">About</a></li>
        <li><a class="navbar-link" href="#teams/index">Teams</a></li>
      </div>

      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
       <button type="submit" class="btn btn-default">Search</button>
      </form>

      <% if signed_in? %>
      <div class="nav navbar-nav navbar-left">
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.fname%><b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li><a href="#user">My paralegals</a></li>
            <li><a href="#myTeams">My teams</a></li>
            <li><a href="#">Messages</a></li>
            <li>
              <% if signed_in? %>
                <li id="signout-button"><%= link_to "Sign out", session_url, { method: :delete } %></li>
              <%else%>
                <li><%= link_to "Sign in", new_session_url, { method: :get, class: "btn btn-xs btn-success" } %></li>
              <% end %>
            </li>


          </ul>
        </li>
      </div>
      <% end %>

      <ul class="nav navbar-nav navbar-left">
        <li>
          <% if !signed_in? && request.env['PATH_INFO'] == "/session/new" %>
            <li><%= button_to "Register", new_user_url, { method: :get, class: "btn btn-xs btn-success" } %></li>
          <% elsif !signed_in? && request.env['PATH_INFO'] == "/users/new" %>
            <li><%= button_to "Sign in", new_session_url, { method: :get, class: "btn btn-xs btn-success" } %></li>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>

<%= yield %>

  <div class="footer container-fluid"> 
    <div class="hidden-elements">
      <div class="container">
        <div class="row">

          <div class="col-md-6 col-md">
            <div id="home-page-info" class="jumbotron">
              <div id="paralegalInfo">
                <div class="page-header" id="about-box">
                  <span id="about-header"> How it works 
                    
                  </h4>
                </div>
                  <ol style="padding-left: 0px">
                    <li class="about-list">
                      <span class="number">1</span>
                      <span class="home-list-item">Read their stories.</span>
                    </li>
                    <li class="about-list">
                      <span class="number">2</span>
                      <span class="home-list-item">Choose one to sponsor.</span>
                    </li>
                    <li class="about-list">
                      <span class="number">3</span>
                      <span class="home-list-item">Follow their progress.</span>
                    </li>
                    <li class="about-list">
                      <span class="number">4</span>
                      <span class="home-list-item">Repeat!</span>
                    </li>
                  </ol>
                  <div>
                    <a href="#paralegals/index" id="home-index-button" > Ready? Find a paralegal!</a>
                  </div>
              </div>
            </div>
          </div>

          <div class="col-md-6 col-md">
            <div id="home-page-info" class="jumbotron">
              <div id="about-block">
                <div class="page-header" id="about-box">
                  <span id="about-header"> About the program <span>
                    <span>
                      <a href="#about" id="about-link">learn more</a>
                    </span>
                </div>
                <div>
                  <span class="home-list-item" id="about-text">
                    In a world where 4 billion people live outside the protection of the law, <a href="http://www.namati.org/about/">Namati</a> is dedicated to putting the law in people’s hands. We’re building a movement of grassroots legal advocates who work with communities to advance justice. These advocates are fighting on the front lines to ensure that people can protect their land, access essential services, and take part in the decisions that govern their lives.
                  <span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="head-strip container-fluid" id="bottom-strip">
    <div class="container-fluid" id="bottom-tagline">Giving changes lives.</div>
  </div>

</body>
</html>